/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package midi;

/**
 *
 * @author Daniel Castillo
 */
public interface Diccionary {
    //para el status byte (primer byte del mensaje)
    public static final int NOTE_ON = 144;
    public static final int NOTE_OFF = 128;
    public static final int POLY_AFTERTOUCH = 160;
    public static final int CONTROL_CHANGE = 176;
    public static final int CHANNEL_AFTERTOUCH = 192;
    public static final int PITCH_BEND = 208;
    public static final int PROGRAM_CHANGE = 224;
    public static final int SYSTEM_MESSAGE = 240;
    //para las notaspublic static final int C3 = 48;
    public static final int C00 = 0;
    public static final int D00b = 1;
    public static final int D00 = 2;
    public static final int E00b = 3;
    public static final int E00 = 4;
    public static final int F00 = 5;
    public static final int G00b = 6;
    public static final int G00 = 7;
    public static final int A0b = 8;
    public static final int A0 = 9;
    public static final int B0b = 10;
    public static final int B0 = 11;
    public static final int C0 = 12;
    public static final int D0b = 13;
    public static final int D0 = 14;
    public static final int E0b = 15;
    public static final int E0 = 16;
    public static final int F0 = 17;
    public static final int G0b = 18;
    public static final int G0 =19;
    public static final int A1b = 20;
    public static final int A1 = 21;
    public static final int B1b = 22;
    public static final int B1 = 23;
    public static final int C1 = 24;
    public static final int D1b = 25;
    public static final int D1 = 26;
    public static final int E1b = 27;
    public static final int E1 = 28;
    public static final int F1 = 29;
    public static final int G1b = 30;
    public static final int G1 = 31;
    public static final int A2b = 32;
    public static final int A2 = 33;
    public static final int B2b = 34;
    public static final int B2 = 35;
    public static final int C2 = 36;
    public static final int D2b = 37;
    public static final int D2 = 38;
    public static final int E2b = 39;
    public static final int E2 = 40;
    public static final int F2 = 41;
    public static final int G2b = 42;
    public static final int G2 = 43;
    public static final int A3b = 44;
    public static final int A3 = 45;
    public static final int B3b = 46;
    public static final int B3 = 47;
    public static final int C3 = 48;
    public static final int D3b = 49;
    public static final int D3 = 50;
    public static final int E3b = 51;
    public static final int E3 = 52;
    public static final int F3 = 53;
    public static final int G3b = 54;
    public static final int G3 = 55;
    public static final int A4b = 56;
    public static final int A4 = 57;
    public static final int B4b = 58;
    public static final int B4 = 59;
    public static final int C4 = 60;
    public static final int D4b = 61;
    public static final int D4 = 62;
    public static final int E4b = 63;
    public static final int E4 = 64;
    public static final int F4 = 65;
    public static final int G4b = 66;
    public static final int G4 = 67;
    public static final int A5b = 68;
    public static final int A5 = 69;
    public static final int B5b = 70;
    public static final int B5 = 71;
    public static final int C5 = 72;
    public static final int D5b = 73;
    public static final int D5 = 74;
    public static final int E5b = 75;
    public static final int E5 = 76;
    public static final int F5 = 77;
    public static final int G5b = 78;
    public static final int G5 = 79;
    public static final int A6b = 80;
    public static final int A6 = 81;
    public static final int B6b = 82;
    public static final int B6 = 83;
    public static final int C6 = 84;
    public static final int D6b = 85;
    public static final int D6 = 86;
    public static final int E6b = 87;
    public static final int E6 = 88;
    public static final int F6 = 89;
    public static final int G6b = 90;
    public static final int G6 = 91;
    public static final int A7b = 92;
    public static final int A7 = 93;
    public static final int B7b =94;
    public static final int B7 = 95;
    public static final int C7 = 96;
    public static final int D7b = 97;
    public static final int D7 = 98;
    public static final int E7b = 99;
    public static final int E7 = 100;
    public static final int F7 = 101;
    public static final int G7b = 102;
    public static final int G7 = 103;
    public static final int A8b = 104;
    public static final int A8 = 105;
    public static final int B8b = 106;
    public static final int B8 = 107;
    public static final int C8 = 108;
    public static final int D8b = 109;
    public static final int D8 = 110;
    public static final int E8b = 111;
    public static final int E8 = 112;
    public static final int F8 = 113;
    public static final int G8b = 114;
    public static final int G8 = 115;
    public static final int A9b = 116;
    public static final int A9 = 117;
    public static final int B9b = 118;
    public static final int B9 = 119;
    public static final int C9 = 120;
    //para CC (Change Control)
    public static final int BANK_CHANGE = 0;
    public static final int MODULATION = 1;
    public static final int VOLUME = 7;
    public static final int BALANCE = 8;
    public static final int PANORAMA = 10;
    public static final int EXPRESSION = 11;
    public static final int SUSTAIN = 64;
    public static final int REVERB = 91;
    public static final int TREMOLO = 92;
    public static final int CHORUS = 93;
    public static final int DETUNE = 94;
    public static final int PHASER = 95;
}
